<?xml version="1.0" encoding="utf-8"?>
<Database Name="C:\ARQUIVOS DE PROGRAMAS\MICROSOFT SQL SERVER\MSSQL.1\MSSQL\DATA\CORRIDAS.MDF" Class="RunningDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=&quot;C:\ARQUIVOS DE PROGRAMAS\MICROSOFT SQL SERVER\MSSQL.1\MSSQL\DATA\CORRIDAS.MDF&quot;;Integrated Security=True" SettingsObjectName="Running.Business.Properties.Settings" SettingsPropertyName="AntigaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.run_Atleta" Member="Atletas">
    <Type Name="Atleta">
      <Column Name="IdAtleta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Apelido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Sexo" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DtNascimento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Fone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(11)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Atleta_Resultado" Member="Resultados" OtherKey="IdAtleta" Type="Resultado" />
    </Type>
  </Table>
  <Table Name="dbo.run_Prova" Member="Provas">
    <Type Name="Prova">
      <Column Name="IdProva" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Etapa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Local" Type="System.String" DbType="VarChar(150)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Organizacao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SiteOficial" Type="System.String" DbType="VarChar(200)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Distancia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Obs" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Prova_Resultado" Member="Resultados" OtherKey="IdProva" Type="Resultado" />
    </Type>
  </Table>
  <Table Name="dbo.run_Resultado" Member="Resultados">
    <Type Name="Resultado">
      <Column Name="IdResultado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Numero" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FaixaEtaria" Type="System.String" DbType="VarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Equipe" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TempoLiq" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TempoOfic" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ClassGeral" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ClassSexo" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ClassFaixa" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TotalClassGeral" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TotalClassSexo" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TotalClassFaixa" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Ritmo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Distancia" Type="System.String" DbType="VarChar(20)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NoLugarDe" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FezInscricao" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IdAtleta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IdProva" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Resultado_Tempo" Member="Tempos" OtherKey="IdResultado" Type="Tempo" />
      <Association Name="Atleta_Resultado" Member="Atleta" ThisKey="IdAtleta" Type="Atleta" IsForeignKey="true" />
      <Association Name="Prova_Resultado" Member="Prova" ThisKey="IdProva" Type="Prova" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.run_Tempo" Member="Tempos">
    <Type Name="Tempo">
      <Column Name="IdTempo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrdemKM" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Volta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Terreno" Type="System.String" DbType="NChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Altimetria" Type="System.String" DbType="NChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Obs" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdResultado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Resultado_Tempo" Member="Resultado" ThisKey="IdResultado" Type="Resultado" IsForeignKey="true" />
    </Type>
  </Table>
</Database>